
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN COLON DOT DOUBLEQUOTE FOR ID INT LBRACE LPAREN LTE NUMBER OUT PLUS PRINTLN RBRACE RPAREN SEMICOLON SYSTEMprogram : declaration statement\n               | statementdeclaration : INT ID SEMICOLONstatement : FOR LPAREN ID ASSIGN NUMBER SEMICOLON ID LTE NUMBER SEMICOLON ID PLUS PLUS RPAREN LBRACE SYSTEM DOT OUT DOT PRINTLN LPAREN ID RPAREN SEMICOLON RBRACEstatement : SYSTEM DOT OUT DOT PRINTLN LPAREN ID RPAREN SEMICOLON'
    
_lr_action_items = {'INT':([0,],[4,]),'FOR':([0,2,11,],[5,5,-3,]),'SYSTEM':([0,2,11,31,],[6,6,-3,32,]),'$end':([1,3,7,25,41,],[0,-2,-1,-5,-4,]),'ID':([4,9,18,19,26,37,],[8,12,20,21,27,38,]),'LPAREN':([5,17,36,],[9,19,37,]),'DOT':([6,13,32,34,],[10,15,33,35,]),'SEMICOLON':([8,16,23,24,39,],[11,18,25,26,40,]),'OUT':([10,33,],[13,34,]),'ASSIGN':([12,],[14,]),'NUMBER':([14,22,],[16,24,]),'PRINTLN':([15,35,],[17,36,]),'LTE':([20,],[22,]),'RPAREN':([21,29,38,],[23,30,39,]),'PLUS':([27,28,],[28,29,]),'LBRACE':([30,],[31,]),'RBRACE':([40,],[41,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'declaration':([0,],[2,]),'statement':([0,2,],[3,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> declaration statement','program',2,'p_program','analizador_lexico.py',69),
  ('program -> statement','program',1,'p_program','analizador_lexico.py',70),
  ('declaration -> INT ID SEMICOLON','declaration',3,'p_declaration','analizador_lexico.py',74),
  ('statement -> FOR LPAREN ID ASSIGN NUMBER SEMICOLON ID LTE NUMBER SEMICOLON ID PLUS PLUS RPAREN LBRACE SYSTEM DOT OUT DOT PRINTLN LPAREN ID RPAREN SEMICOLON RBRACE','statement',25,'p_statement_for','analizador_lexico.py',79),
  ('statement -> SYSTEM DOT OUT DOT PRINTLN LPAREN ID RPAREN SEMICOLON','statement',9,'p_statement_println','analizador_lexico.py',94),
]
